CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS public.users
(
    id        BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    username  VARCHAR NOT NULL UNIQUE,
    password  VARCHAR NOT NULL,
    email     VARCHAR NOT NULL UNIQUE,
    role      VARCHAR NOT NULL,

    createdAt  TIMESTAMP WITH TIME ZONE NOT NULL,
    updatedAt TIMESTAMP WITH TIME ZONE
);