services:
  user_service:
    build:
      context: .
      dockerfile: ./UserService/Dockerfile
    container_name: user_service
    ports:
      - "8080:8080"
    environment:
      - 'DB_USERNAME=admin'
      - 'DB_PASSWORD=admin'
      - 'DB_URL=jdbc:postgresql://user_db:5432/spaceStationUser'
      - 'PORT=8080'
    depends_on:
      user_db:
        condition: service_healthy

  user_db:
    image: postgres:15
    container_name: user_db
    environment:
      - 'POSTGRES_DB=spaceStationUser'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=admin'
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 10s
      timeout: 5s
      retries: 5

  wiki_core_service:
    build:
      context: .
      dockerfile: ./WikiCoreService/Dockerfile
    container_name: wiki_core_service
    ports:
      - "8081:8081"
    environment:
      - 'DB_USERNAME=admin'
      - 'DB_PASSWORD=admin'
      - 'DB_URL=jdbc:postgresql://article_db:5432/spaceStationArticle'
      - 'PORT=8081'
    depends_on:
      article_db:
        condition: service_healthy

  article_db:
    image: postgres:15
    container_name: article_db
    environment:
      - 'POSTGRES_DB=spaceStationArticle'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=admin'
    ports:
      - "5431:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 10s
      timeout: 5s
      retries: 5

