spring:
  application:
    name: WikiCoreService
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/spaceStationCore}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: "init"
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka1:29092,kafka2:29093}
    consumer:
      group-id: ${spring.application.name}-group
      auto-offset-reset: earliest
    properties:
      spring.json.trusted.packages: "*"

server:
  port: ${PORT:8081}
